### ISSUE TITLE
About ["contrastive", "direct", "contrastive_text", "direct_text"].

### ISSUE THREAD

**Issue by Robin-WZQ** [technion-cs-nlp/ReFACT#1]
Dear authors,

I'm really interested in your work and I am sure I will follow your work!

But there is a simple question when I scan your code. What are ["contrastive", "direct", "contrastive_text", "direct_text"] mean? What's difference between them?

Thanks!

**Comment by danaarad** [comment]
Hi, thanks for your interest! 
In our paper we present various algorithms, and the flag is used to select which variation will be executed. The primary results in our paper are obtained using the "contrastive_text" algorithm. You can find details on the differences between the methods and experiments in the paper.

**Comment by Robin-WZQ** [comment]
I see, thanks!
